# Generated by Django 3.2.6 on 2021-09-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0012_rename_crated_date_shoppingcomment_created_date'),
        ('order', '0002_alter_shopcart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=14)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Qəbul edilmiş'), ('Preaparing', 'Hazırlanır'), ('OnShipping', 'Karqoda'), ('Completed', 'Təhvil verilib'), ('Canceled', 'Ləğv edilmiş')], default='New', max_length=50)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('adminNote', models.CharField(blank=True, max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_ad', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProdcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiyy', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Qəbul edilmiş'), ('Canceled', 'Ləğv edilmiş')], default='New', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_ad', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppings.product')),
            ],
        ),
    ]
