# Generated by Django 3.2.6 on 2021-09-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderprodcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderprodcat',
            old_name='quantiyy',
            new_name='quantity',
        ),
    ]
