# Generated by Django 3.2.6 on 2021-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0012_rename_crated_date_shoppingcomment_created_date'),
        ('order', '0004_rename_quantiyy_orderprodcat_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProdcat',
            new_name='OrderProduct',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Adresiniz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Şəhər'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Adınız'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyadınız'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Əlaqə nömrəsi'),
        ),
    ]
