# Generated by Django 3.2.6 on 2021-10-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yeni', 'New'), ('Qəbul edilmiş', 'Accepted'), ('Hazırlanır', 'Preaparing'), ('Karqoda', 'OnShipping'), ('Təhvil verilib', 'Completed'), ('Ləğv edilmiş', 'Canceled')], default='New', max_length=50),
        ),
    ]
