# Generated by Django 3.2.6 on 2021-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Qəbul edilmiş'), ('Preaparing', 'Hazırlanır'), ('OnShipping', 'Karqoda'), ('Completed', 'Təhvil verilib'), ('Canceled', 'Ləğv edilmiş')], default='Yeni', max_length=50),
        ),
    ]
