# Generated by Django 3.2.6 on 2021-10-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Yeni', 'New'), ('Qəbul edilmiş', 'Accepted'), ('Ləğv edilmiş', 'Canceled')], default='New', max_length=20),
        ),
    ]
