# Generated by Django 3.2.6 on 2021-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_center', '0002_auto_20210913_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
