# Generated by Django 3.2.6 on 2021-09-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_center', '0003_auto_20210913_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Bazar ertəsi'), (2, 'Çərşənbə axşamı'), (3, 'Çərşənbə'), (4, 'Cümə axşamı'), (5, 'Cümə'), (6, 'Şənbə'), (7, 'Bazar')])),
                ('work_day_hours', models.CharField(max_length=5)),
                ('gym_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_center.gymcenter')),
            ],
        ),
    ]
