# Generated by Django 3.2.6 on 2021-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_center', '0008_gymcenter_center_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day_of_week',
            field=models.CharField(choices=[(1, 'Bazar ertəsi'), (2, 'Çərşənbə axşamı'), (3, 'Çərşənbə'), (4, 'Cümə axşamı'), (5, 'Cümə'), (6, 'Şənbə'), (7, 'Bazar')], max_length=50),
        ),
    ]
