# Generated by Django 3.2.6 on 2021-10-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_center', '0011_alter_workday_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcenter',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
