# Generated by Django 3.2.6 on 2021-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_images', models.FileField(blank=True, upload_to='', verbose_name='Sekil elave edin')),
                ('carousel_title', models.CharField(max_length=50)),
                ('carousel_content', models.CharField(max_length=100)),
                ('carousel_button', models.CharField(max_length=20)),
            ],
        ),
    ]
