# Generated by Django 3.2.6 on 2021-09-11 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210902_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_images',
            field=models.FileField(null=True, upload_to='', verbose_name='Sekil elave edin'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
