# Generated by Django 3.2.6 on 2021-09-15 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_likearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
