# Generated by Django 3.2.6 on 2021-10-05 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_comments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likearticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
