# Generated by Django 3.2.6 on 2021-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20211005_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articles_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
