# Generated by Django 3.2.6 on 2021-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
