# Generated by Django 3.2.6 on 2021-10-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rate',
        ),
    ]
