# Generated by Django 3.2.6 on 2021-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_remove_article_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
