# Generated by Django 3.2.6 on 2021-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(default='Şikayət', max_length=50),
        ),
    ]
