# Generated by Django 3.2.6 on 2021-10-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_ours_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ours_contact',
            name='ours_coordinate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
