# Generated by Django 3.2.6 on 2021-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0003_auto_20210906_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
