# Generated by Django 3.2.6 on 2021-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0005_shoppingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcomment',
            name='comment_author',
            field=models.EmailField(max_length=254),
        ),
    ]
