# Generated by Django 3.2.6 on 2021-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0006_alter_shoppingcomment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcomment',
            name='comment_author',
            field=models.EmailField(max_length=254, verbose_name='Emailinizi yazin'),
        ),
    ]
