# Generated by Django 3.2.6 on 2021-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0007_alter_shoppingcomment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcomment',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
