# Generated by Django 3.2.6 on 2021-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0008_alter_shoppingcomment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcomment',
            name='comment_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Emailinizi yazin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcomment',
            name='comment_author',
            field=models.CharField(max_length=100, verbose_name='Adınızı qeyd edin'),
        ),
    ]
