# Generated by Django 3.2.6 on 2021-09-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0011_alter_shoppingcomment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcomment',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
