# Generated by Django 3.2.6 on 2021-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0014_auto_20211005_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
